# Generated by Django 6.0.4 on 2026-05-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='origin_country',
            field=models.CharField(default='', max_length=120),
        ),
    ]
