# Generated by Django 6.0.4 on 2026-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_origin_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
