# Generated by Django 6.0.4 on 2026-06-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_pricing_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='trip',
            name='selected_flight',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='selected_hotel',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
