# Generated by Django 6.0.4 on 2026-06-24 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('refund', 'Refund'), ('modify', 'Modify')], max_length=10)),
                ('status', models.CharField(choices=[('awaiting_confirmation', 'Awaiting confirmation'), ('executed', 'Executed'), ('denied', 'Denied by policy'), ('declined', 'Declined by user'), ('failed', 'Failed')], default='awaiting_confirmation', max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('policy_basis', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('mode', models.CharField(choices=[('assist', 'Assist'), ('individual', 'Individual')], default='assist', max_length=12)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_offer',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'REFUNDED']), _negated=True), fields=('user', 'kind', 'offer_id'), name='unique_active_booking_per_offer'),
        ),
        migrations.AddField(
            model_name='supportoperation',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_operations', to='trips.booking'),
        ),
        migrations.AddField(
            model_name='supportoperation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportoperation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='trips.supportsession'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trips.supportsession'),
        ),
    ]
