from django.urls import path

from .views import (
    ChatSessionDetailView,
    ChatSessionListCreateView,
    CurrentTripView,
    SupportSessionDetailView,
    SupportSessionListCreateView,
    TripDetailView,
    TripListCreateView,
    budget_country_tiers,
    chat_end_session,
    chat_send_message,
    destination_weather,
    evaluate_budget,
    flight_search,
    geonames_search,
    hotel_booking,
    hotel_search,
    support_confirm_operation,
    support_decline_operation,
    support_send_message,
)

urlpatterns = [
    path("", TripListCreateView.as_view(), name="trip-list-create"),
    path("current/", CurrentTripView.as_view(), name="trip-current"),
    path("geonames/", geonames_search, name="geonames-search"),
    path("budget/tiers/", budget_country_tiers, name="budget-country-tiers"),
    path("budget/evaluate/", evaluate_budget, name="budget-evaluate"),
    path("weather/", destination_weather, name="destination-weather"),
    path("flights/search/", flight_search, name="flight-search"),
    path("hotels/search/", hotel_search, name="hotel-search"),
    path("bookings/", hotel_booking, name="hotel-booking"),
    path("chat/sessions/", ChatSessionListCreateView.as_view(), name="chat-session-list"),
    path("chat/sessions/<int:pk>/", ChatSessionDetailView.as_view(), name="chat-session-detail"),
    path("chat/sessions/<int:pk>/messages/", chat_send_message, name="chat-send-message"),
    path("chat/sessions/<int:pk>/end/", chat_end_session, name="chat-end-session"),
    path("support/sessions/", SupportSessionListCreateView.as_view(), name="support-session-list"),
    path("support/sessions/<int:pk>/", SupportSessionDetailView.as_view(), name="support-session-detail"),
    path("support/sessions/<int:pk>/messages/", support_send_message, name="support-send-message"),
    path("support/operations/<int:op_id>/confirm/", support_confirm_operation, name="support-confirm-op"),
    path("support/operations/<int:op_id>/decline/", support_decline_operation, name="support-decline-op"),
    path("<int:pk>/", TripDetailView.as_view(), name="trip-detail"),
]
